[package]
name = "x12-types"
version = "0.3.0"
edition = "2021"
authors = ["Jens Walter <jens@apimeister.com>"]
license = "MIT OR Apache-2.0"
keywords = ["edi","x12"]
repository = "https://github.com/apimeister/x12-types/"
documentation = "https://docs.rs/x12-types/"
description = "Bindings for the ANSI X12 EDI definitions"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_x12 = { version = "0.2" }

[features]
default = ["v003030","v004010","v004030","v005030"]
v003030 = []
v004010 = []
v004030 = []
v005030 = []
